# Generated by Django 3.0.7 on 2020-06-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nick_name',
            field=models.CharField(max_length=10, null=True, verbose_name='昵称'),
        ),
    ]
