# Generated by Django 3.0.7 on 2020-06-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Available_integral',
            field=models.IntegerField(blank=True, null=True, verbose_name='可用积分'),
        ),
        migrations.AlterField(
            model_name='member',
            name='card_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='开卡金额'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='会员地址'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='会员生日'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机号码'),
        ),
    ]
