# Generated by Django 3.0.7 on 2020-06-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_auto_20200615_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='card_money',
            field=models.IntegerField(default=0, verbose_name='开卡金额'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='会员地址'),
        ),
    ]
