# Generated by Django 3.0.7 on 2020-06-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_auto_20200619_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='supplier_goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='supplier',
            field=models.ForeignKey(default='4343', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_goods', to='systemapp.Supplier'),
        ),
    ]
