# Generated by Django 3.0.7 on 2020-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_auto_20200615_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_birthday',
            field=models.DateField(verbose_name='会员生日'),
        ),
    ]
