# Generated by Django 3.0.7 on 2020-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0004_auto_20200615_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='buying_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='进货价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='retail_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='零售价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='specs',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='商品规格'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='entry_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='iphone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.CharField(blank=True, default=8000, max_length=20, null=True, verbose_name='薪酬'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contacts_iphone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
