# Generated by Django 3.0.7 on 2020-06-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0004_auto_20200619_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_goods', to='systemapp.Supplier'),
        ),
    ]
