# Generated by Django 3.0.7 on 2020-06-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0007_auto_20200621_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='systemapp.Supplier'),
        ),
    ]
